### ISSUE TITLE
Storybook 8 migratie themes repo

### ISSUE THREAD

**Issue by Yolijn** [nl-design-system/themes#518]
Afhankelijk van #516 en #517 

- [ ] MDX stories naar TSX
- [ ] Webpack naar Vite
- [ ] ...

**Comment by Robbert** [comment]
## Brainfart

Relevante commits:

https://github.com/nl-design-system/utrecht/pull/1744/commits/ffcba30abdf38a0d5eb968b695c304f8ca2df59f
https://github.com/nl-design-system/utrecht/pull/1744/commits/57b2123e3a20f98b5883dcd3f8dfb6f920afc53a
https://github.com/nl-design-system/utrecht/pull/1744/commits/a26c3d1096381a5cbfa113b7569f33d219db43bf

Je moet ook van mdx naar mdx2 migreren, daarvoor moeten sommige dingen aangepast worden in markdown files: https://github.com/nl-design-system/utrecht/pull/1459/commits/5d491a45996a5dfe38843f7ca27bc9894c64093b

We moesten wat extra babelrc files toevoegen: https://github.com/nl-design-system/utrecht/pull/1459/commits/609eccf1b47407be4ec104a5f476f2277a741d68

We moesten ook alle .mdx bestanden naar binnen packages/storybook/: https://github.com/nl-design-system/example/pull/21

De startup command moet aangepast worden:
"storybook": "storybook dev

Je kunt automigrations doen die sommige dingen oplossen:
https://storybook.js.org/docs/migration-guide

storyStoreV7: false zou niet meer nodig moeten zijn denk ik

Voor sommige problemen was het nodig dit te doen:
https://github.com/nl-design-system/utrecht/pull/1487/files#diff-037405657d5a8abc236372da51d67e1a30b66d317c8faed1867b2269f10f8802

Check even alle addons (of disable ze allemaal om mee te beginnen) of ze wel compatible zijn met Storybook 7

**Comment by Robbert** [comment]
Wohoo, done!
