### ISSUE TITLE
Composite tokens worden nog niet goed vertaald naar css

### ISSUE THREAD

**Issue by RGRMdesign** [nl-design-system/themes#788]
Composite tokens komen nu nog als Object in de css. Zie bijvoorbeeld:

```
--voorbeeld-box-shadow-lg: [object Object];
--voorbeeld-box-shadow-md: [object Object];
--voorbeeld-box-shadow-sm: [object Object];
```

Is er al een implementatie van Style Dictionary waarin dit werkt? Kunnen we dit globaal maken?

**Comment by YOUR1** [comment]
@Robbert kun je dit checken? Dit is namelijk wel erg hinderlijk.
